---
title: "Piccirillo_data_analysis"
author: "lfp"
date: "2025-12-01"
output: html_document
---

```{r}
# Install and load packages
#install.packages("tidyverse")
#install.packages("here")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("sf")
#install.packages("mapview")
#install.packages("leaflet")
#install.packages("corrplot")
#install.packages("cowplot")
library(tidyverse)
library(here)
library(ggplot2)
library(lubridate)
library(sf)
library(mapview)
library(leaflet)
library(corrplot)
library(cowplot)

# Set your working directory
setwd("~/ENV 872/Final Project/Piccirillo_ENV872_EDA_FinalProject")
getwd()
here()

# Set your ggplot theme
mytheme <- theme_bw() + theme(axis.text = element_text(color = "black"),
                              legend.position = "top",
                              legend.text = element_text(color = "black"))
theme_set(mytheme)

```


```{r}
# uploading dataset
all_data <- read.csv(here("Data/Processed/se_oxygen_processed.csv"),
                     stringsAsFactors = T)

# multiple linear regression model of SELENITE compared to depth & oxygen
# using multiple linear regressions because continuous response/continuous explanatory
selenite_lm <- lm(data = all_data, 
                  Se_IV_D_CONC_BOTTLE ~ depth + meanOxygen)
summary(selenite_lm)

# checking fit of the model
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(selenite_lm)
par(mfrow = c(1,1))

# correlation plot
selenite_cor <- all_data %>%
  select(Se_IV_D_CONC_BOTTLE, depth, meanOxygen) %>%
  na.omit()

selenite_correlation <- cor(selenite_cor)
corrplot(selenite_correlation, method = 'ellipse')

# plotting the linear regression
a <- ggplot(all_data, aes(depth, Se_IV_D_CONC_BOTTLE)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  labs(x = "Depth (m)", y = "SeIV Concentration (nm/L)", 
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenite (SeIV) vs. Depth")

# visualizing from oceanography perspective
b <- ggplot(all_data, aes(Se_IV_D_CONC_BOTTLE, depth)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  scale_y_reverse() +
  labs(y = "Depth (m)", x = "SeIV Concentration (nm/L)", 
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenite (SeIV) vs. Depth")

# grid the above plots for report
plot_grid(a, b, labels = "AUTO")

# oxygen vs selenite plot 
ggplot(all_data, aes(meanOxygen, Se_IV_D_CONC_BOTTLE)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  labs(x = "Dissolved oxygen (umol/kg)", y = "SeIV Concentration (nm/L)", 
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenite (SeIV) vs. Dissolved Oxygen")

```


```{r}
# multiple linear regression model of SELENATE compared to depth
selenate_lm <- lm(data = all_data, 
                  Se_VI_D ~ depth + meanOxygen)
summary(selenate_lm)

# checking fit of model
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(selenate_lm)
par(mfrow = c(1,1))

# correlation plot
selenate_cor <- all_data %>%
  select(Se_VI_D, depth, meanOxygen) %>%
  na.omit()

selenate_correlation <- cor(selenate_cor)
corrplot(selenate_correlation, method = 'ellipse')

# plotting the linear regression
x <- ggplot(all_data, aes(depth, Se_VI_D)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  labs(x = "Depth (m)", y = "SeVI Concentration (nm/L)",
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenate (SeVI) vs. Depth")

# visualizing it as oceanographic data
y <- ggplot(all_data, aes(Se_VI_D, depth)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  scale_y_reverse(limits = c(6000, 0)) +
  labs(y = "Depth (m)", x = "SeVI Concentration (nm/L)",
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenate (SeVI) vs. Depth")

# grid the above plots for report
plot_grid(x, y, labels = "AUTO")

# oxygen vs selenate plot 
ggplot(all_data, aes(meanOxygen, Se_VI_D)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  labs(x = "Dissolved oxygen (umol/kg)", y = "SeVI Concentration (nm/L)", 
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenate (SeIV) vs. Dissolved Oxygen")

```


```{r}
# multiple linear regression model of organic selenide compared to depth & oxygen
selenide_lm <- lm(data = all_data, 
                  Org_Se_II_CONC_BOTTLE ~ depth + meanOxygen)
summary(selenide_lm)

par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(selenide_lm)
par(mfrow = c(1,1))

# correlation plot
selenide_cor <- all_data %>%
  select(Org_Se_II_CONC_BOTTLE, depth, meanOxygen) %>%
  na.omit()

selenide_correlation <- cor(selenide_cor)
corrplot(selenide_correlation, method = 'ellipse')

# plotting the linear regression
z <- ggplot(all_data, aes(depth, Org_Se_II_CONC_BOTTLE)) + 
  geom_point(alpha = 0.7, size = 2.5) + 
  labs(x = "Depth (m)", y = "Se2- Concentration (nm/L)", 
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Organic Selenide (Se2-) vs. Depth")

# visualizing as oceanographic data
aa <- ggplot(all_data, aes(Org_Se_II_CONC_BOTTLE, depth)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  scale_y_reverse() + labs(y = "Depth (m)", x = "Se2- Concentration (nm/L)",
                           subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Organic Selenide (Se2-) vs. Depth")

# grid above plots for report
plot_grid(z, aa, labels = "AUTO")

# oxygen vs selenide plot 
ggplot(all_data, aes(meanOxygen, Org_Se_II_CONC_BOTTLE)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  labs(x = "Dissolved oxygen (umol/kg)", y = "SeVI Concentration (nm/L)", 
       subtitle = "All Locations from GP16 Cruise") + 
  geom_smooth(method = lm, se = F) + 
  ggtitle(label = "Selenide (Se2-) vs. Dissolved Oxygen")

```


```{r}
# pivot longer dataset to plot all Se species together with depth
all_data_gathered <- pivot_longer(all_data, 
                                  Se_IV_D_CONC_BOTTLE:Org_Se_II_CONC_BOTTLE, 
               names_to = "species", values_to = "concentration")

ggplot(all_data_gathered, aes(concentration, depth, colour = species)) + 
  geom_point(alpha = 0.4, size = 2.5) + scale_y_reverse(limits = c(6000, 0)) + 
  geom_smooth(method = lm, se = F, linewidth = 1.9) + 
  labs(y = "Depth (m)", x = "Concentration (nm/L)", 
       color = "Selenium species") + scale_color_viridis_d(
         labels = c("Organic Selenide", "Selenite", "Selenate"))

# plotting all species together with oxygen
ggplot(all_data_gathered, aes(meanOxygen, concentration, colour = species)) + 
  geom_point(alpha = 0.4, size = 2.5) + 
  geom_smooth(method = lm, se = F, linewidth = 1.9) + 
  labs(x = "Dissolved Oxygen (umol/kg)", y = "Concentration (nm/L)", 
       color = "Selenium species") + scale_color_viridis_d(
         labels = c("Organic Selenide", "Selenite", "Selenate"))

```


```{r}
#OMZ location analysis
OMZ_only <- read.csv(here("Data/Processed/OMZ_data_processed.csv"),
                     stringsAsFactors = T)

# multiple linear regression for only 2 OMZ locations - selenite
OMZ_selenite_lm <- lm(data = OMZ_only, 
                      Se_IV_D_CONC_BOTTLE ~ depth + Sbeox0)
summary(OMZ_selenite_lm)

# checking fit of model
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(OMZ_selenite_lm)
par(mfrow = c(1,1))

# multiple linear regression for only 2 OMZ locations - selenate
OMZ_selenate_lm <- lm(data = OMZ_only, 
                      Se_VI_D ~ depth + Sbeox0)
summary(OMZ_selenate_lm)

# checking fit of model
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(OMZ_selenate_lm)
par(mfrow = c(1,1))

# multiple linear regression for only 2 OMZ locations - selenide
OMZ_selenide_lm <- lm(data = OMZ_only, 
                      Org_Se_II_CONC_BOTTLE ~ depth + Sbeox0)
summary(OMZ_selenide_lm)

# checking fit of model
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(OMZ_selenide_lm)
par(mfrow = c(1,1))

# plotting oxygen for grid
bb <- ggplot(OMZ_only, aes(Sbeox0, depth)) + geom_point(size = 2.5) + 
  scale_y_reverse() +
  labs(x = 'Dissolved Oxygen (umol/kg)', y = 'Depth (m)')

# plotting selenide vs depth
cc <- ggplot(OMZ_only, aes(Org_Se_II_CONC_BOTTLE, depth)) + geom_point(size = 2.5) + scale_y_reverse() + geom_smooth(method = lm, se = F) + 
  labs(x = 'Concentration (nm/L)', y = 'Depth (m)')

plot_grid(bb, cc, labels = "AUTO")

# plotting selenide vs oxygen
ggplot(OMZ_only, aes(Sbeox0, Org_Se_II_CONC_BOTTLE)) + geom_point(size = 2.5) + 
  geom_smooth(method = lm, se = F) + 
  labs(x = "Dissolved Oxygen (umol/kg)", y = "Concentration (nm/L)")
```


```{r}
# plot cruise track locations w/Se data & OMZ locations in a different color
oxygen_OMZ_locations_map <- rbind(all_data, OMZ_only)
  
# convert data file into shapefile for spatial exploration
all_data_sf <- all_data %>%
  st_as_sf(coords = c('EVENT_LON','EVENT_LAT'), crs=4269)

OMZ_only_sf <- OMZ_only %>%
  st_as_sf(coords = c('EVENT_LON','EVENT_LAT'), crs=4269)

# mapview plot
mapview(all_data_sf) + mapview(OMZ_only_sf, color = 'red', col.regions = 'red')
```

