---
title: "Piccirillo_data_exploration"
author: "Laura Piccirillo"
date: "2025-12-01"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Install and load your packages
#install.packages("tidyverse")
#install.packages("here")
#install.packages("ggplot2")
#install.packages("lubridate")
library(tidyverse)
library(here)
library(ggplot2)
library(lubridate)

# Set your working directory
setwd("~/ENV 872/Final Project/Piccirillo_ENV872_EDA_FinalProject")
getwd()
here()

# Set your ggplot theme
mytheme <- theme_bw() + theme(axis.text = element_text(color = "black"),
                              legend.position = "top",
                              legend.text = element_text(color = "black"))
theme_set(mytheme)

# Load your datasets
selenium_conc <- read.csv(here(
  "Data/Raw/As_Se_IO_BOTTLE.csv"), 
                          stringsAsFactors = T)
oxygen <- read.csv(
  here(
  "Data/Raw/GT-C_SBE_CTD_Proc_v30Oct2014.csv"),
  stringsAsFactors = T)

```


```{r, investigate selenium dataset}
# explore dataset
dim(selenium_conc)
glimpse(selenium_conc)

# check class of selenium concentrations for each species and depth
class(selenium_conc$Se_IV_D_CONC_BOTTLE)
class(selenium_conc$Se_VI_D)
class(selenium_conc$Org_Se_II_CONC_BOTTLE)
class(selenium_conc$depth)

# changing missing values indicated by "nd" to NAs
selenium_conc$Se_IV_D_CONC_BOTTLE <- na_if(
  selenium_conc$Se_IV_D_CONC_BOTTLE, "nd")
sum(is.na(selenium_conc$Se_IV_D_CONC_BOTTLE))
nrow(selenium_conc)
selenium_conc$Se_IV_D_CONC_BOTTLE <- as.numeric(as.character(
  selenium_conc$Se_IV_D_CONC_BOTTLE))

selenium_conc$Se_VI_D <- na_if(
  selenium_conc$Se_VI_D, "nd")
sum(is.na(selenium_conc$Se_VI_D))
selenium_conc$Se_VI_D <- as.numeric(as.character(
  selenium_conc$Se_VI_D))

selenium_conc$Org_Se_II_CONC_BOTTLE <- na_if(
  selenium_conc$Org_Se_II_CONC_BOTTLE, "nd")
sum(is.na(selenium_conc$Org_Se_II_CONC_BOTTLE))
selenium_conc$Org_Se_II_CONC_BOTTLE <- as.numeric(as.character(
  selenium_conc$Org_Se_II_CONC_BOTTLE))

# recheck class of selenium species has been changed to numeric
class(selenium_conc$Se_IV_D_CONC_BOTTLE)
class(selenium_conc$Se_VI_D)
class(selenium_conc$Org_Se_II_CONC_BOTTLE)

# look at distribution of values for total Se and each species
summary(selenium_conc$Se_IV_D_CONC_BOTTLE)
summary(selenium_conc$Se_VI_D)
summary(selenium_conc$Org_Se_II_CONC_BOTTLE)

# change date column to date object
selenium_conc$PI_DATE <- ymd(selenium_conc$PI_DATE)

```


```{r, investigate oxygen dataset}
# explore dataset
dim(oxygen)
glimpse(oxygen)

# check class of oxygen values
class(oxygen$Sbeox0)
class(oxygen$DepSM)

# change date column to date object
oxygen$DATE <- ymd(oxygen$DATE)

# look at distribution of oxygen values
summary(oxygen$Sbeox0)

```


```{r, plotting selenium dataset for exploration}
# visualizing continuous variables of concentrations and depth
seIV_plot <- ggplot(selenium_conc, aes(Se_IV_D_CONC_BOTTLE, depth)) + geom_point() +
  scale_y_reverse(limits = c(6000, 0)) + 
  labs(y = "Depth (m)", x = "SeIV Concentration (nm/L)") + 
  geom_smooth(method = lm, se = F)

# remove outliers row 344
selenium_conc$Se_IV_D_CONC_BOTTLE[344] <- NA

# remove zeroes from Se concentrations - data can never truly be 0. Setting them to NA (figured this out with the help function of na_if)
selenium_conc <- selenium_conc %>%
  mutate(across(c(Se_IV_D_CONC_BOTTLE, Se_VI_D, Org_Se_II_CONC_BOTTLE), 
                ~na_if(., 0)))

# retry plot after outlier set to NA and zeroes removed
seIV_plot_again <- ggplot(selenium_conc, aes(Se_IV_D_CONC_BOTTLE, depth)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  scale_y_reverse(limits = c(6000, 0)) + 
  labs(y = "Depth (m)", x = "SeIV Concentration (nm/L)") + 
  geom_smooth(method = lm, se = F)

seVI_plot <- ggplot(selenium_conc, aes(Se_VI_D, depth)) + 
  geom_point(alpha = 0.7, size = 2.5) + 
  labs(y = "Depth (m)", x = "SeVI Concentration (nm/L)") +
  geom_smooth(method = lm, se = F) +
  scale_y_reverse(limits = c(6000, 0))

org_Se_plot <- ggplot(selenium_conc, aes(Org_Se_II_CONC_BOTTLE, depth)) + 
  geom_point(alpha = 0.7, size = 2.5) +
  scale_y_reverse() + labs(y = "Depth (m)", x = "Se2- Concentration (nm/L)") + 
  geom_smooth(method = lm, se = F)

# comparing frequency of continuous variables (concentrations) 
ggplot(selenium_conc) + geom_density(aes(x = Se_IV_D_CONC_BOTTLE)) + 
  geom_density(aes(x = Se_VI_D), color = "blue") + 
  geom_density(aes(x = Org_Se_II_CONC_BOTTLE), color = "orange") + 
  labs(x = "Concentration (nm/L)", y = "Count") + 
  geom_text(x = 0.45, y = 2.25, label = "Organic Se 2-", color = "orange", size = 5) + 
  geom_text(x = 0.5, y = 1.35, label = "SeIV", size = 5) +
  geom_text(x = 1.25, y = 0.85, label = "SeVI", color = "blue", size = 5)
```

```{r, plotting oxygen dataset for exploration}

ggplot(oxygen, aes(Sbeox0, DepSM)) + geom_point()

```


```{r}
write.csv()
```


```{r, look at locations of casts}
#convert data file into shapefile for spatial exploration
gage_sf <- gage_locations %>%
  st_as_sf(coords = c('dec_long_va','dec_lat_va'), crs=4269)
```

