---
title: "Piccirillo_data_processing"
author: "lfp"
date: "2025-12-01"
output: pdf_document
---
```{r setup, include=FALSE}
# Install and load packages
#install.packages("tidyverse")
#install.packages("here")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("sf")
#install.packages("mapview")
#install.packages("leaflet")
library(tidyverse)
library(here)
library(ggplot2)
library(lubridate)
library(sf)
library(mapview)
library(leaflet)

# Set your working directory
setwd("~/ENV 872/Final Project/Piccirillo_ENV872_EDA_FinalProject")
getwd()
here()

# Set your ggplot theme
mytheme <- theme_bw() + theme(axis.text = element_text(color = "black"),
                              legend.position = "top",
                              legend.text = element_text(color = "black"))
theme_set(mytheme)
```


```{r selenium dataset processing}
# uploading selenium dataset and selecting columns of interest
selenium_clean <- read.csv(here("Data/Processed/As_Se_IO_BOTTLE_Explored.csv"),
                           stringsAsFactors = T)
  
selenium_clean <- selenium_clean %>%
  select(EVENT_LAT, EVENT_LON, PI_DATE, depth, 
         Se_IV_D_CONC_BOTTLE:Org_Se_II_CONC_BOTTLE)

# change date to date object
selenium_clean$PI_DATE <- ymd(selenium_clean$PI_DATE)

# removing rows with NAs for all 3 Se species ONLY
sum(is.na(selenium_clean$Org_Se_II_CONC_BOTTLE))
sum(is.na(selenium_clean$Se_VI_D))
sum(is.na(selenium_clean$Se_IV_D_CONC_BOTTLE))

selenium_clean2 <- selenium_clean %>%
  filter(
    !is.na(Se_IV_D_CONC_BOTTLE) | !is.na(Se_VI_D) | 
      !is.na(Org_Se_II_CONC_BOTTLE))
  
```


```{r oxygen dataset processing}
# uploading oxygen data and selecting columns of interest
oxygen_clean <- read.csv(here(
  "Data/Processed/GT-C_SBE_CTD_Proc_v30Oct2014_Explored.csv"),
  stringsAsFactors = T)

oxygen_clean2 <- oxygen_clean %>%
  select(DATE, LATITUDE, LONGITUDE, DepSM, Sbeox0)

# filter depths of interest for oxygen data 100-500m
#oxygen_clean2 <- oxygen_clean %>%
  #filter(DepSM <= 500)
# decided not to do this after trying to analyze data and not having 
#enough oxygen points

ggplot(oxygen_clean2, aes(Sbeox0, DepSM)) + geom_point() + scale_y_reverse()

```


```{r, look at locations of casts for oxygen}
# trying to combine data with all locations having oxygen data instead of choosing 2 locations - more robust oxygen data for analysis

oxygen_clean2$LATITUDE <- round(oxygen_clean2$LATITUDE, digits = 3)
oxygen_clean2$LONGITUDE <- round(oxygen_clean2$LONGITUDE, digits = 3)
selenium_clean2$EVENT_LAT <- round(selenium_clean2$EVENT_LAT, digits = 3)
selenium_clean2$EVENT_LON <- round(selenium_clean2$EVENT_LON, digits = 3)


trying_something <- left_join(
  selenium_clean2, oxygen_clean2, 
  join_by(EVENT_LAT == LATITUDE, EVENT_LON == LONGITUDE, depth == DepSM))

```


```{r}
# rounding lat/long in oxygen data to 4 decimals to match selenium data lat/long structure
oxygen_clean2$LATITUDE <- round(oxygen_clean2$LATITUDE, digits = 4)
oxygen_clean2$LONGITUDE <- round(oxygen_clean2$LONGITUDE, digits = 4)

# choose locations of interest - picked points with nearly complete depth profiles of oxygen and filtered them by lat/long - picked ones closest to Peruvian coast as this is where OMZ is - only 2 really met requirements. Also looked for locations with Se data!
oxygen_location1 <- oxygen_clean2 %>%
  filter(LATITUDE == -12.0057 & LONGITUDE == -79.1952)

#long of -77.8180 vs -77.8181 assumed to be the same here
oxygen_location2 <- oxygen_clean2 %>%
  filter(LATITUDE == -12.0448 & LONGITUDE == -77.8180)

# checking oxygen depth profiles to confirm locations are in OMZ
ggplot(oxygen_location1, aes(Sbeox0, DepSM)) + geom_point() + 
  scale_y_reverse() + labs(x = "Dissolved Oxygen (umol/kg)", y = "Depth (m)")
ggplot(oxygen_location2, aes(Sbeox0, DepSM)) + geom_point() + 
  scale_y_reverse() + labs(x = "Dissolved Oxygen (umol/kg)", y = "Depth (m)")

# plot these locations to see where they are
oxygen_location_all <- rbind(oxygen_location1, oxygen_location2)
  
# convert data file into shapefile for spatial exploration
oxygen_location_all_sf <- oxygen_location_all %>%
  st_as_sf(coords = c('LONGITUDE','LATITUDE'), crs=4269)

mapview(oxygen_location_all_sf)
```


```{r}
# changing decimal places in depth for Se data
selenium_clean2$depth <- round(selenium_clean2$depth, digits = 0)

# merge not successful because of decimal places. Changing Se data for only one long to be 3 decimal places so merge with oxygen works.
selenium_clean2$EVENT_LON[51:62] <- -77.818

# combining datasets
all_clean <- left_join(
  selenium_clean2, oxygen_location_all, 
  join_by(EVENT_LAT == LATITUDE, EVENT_LON == LONGITUDE, depth == DepSM))

```


```{r}
# saving processed and combined dataset
write.csv(all_clean, row.names = F, 
          "./Data/Processed/se_oxygen_processed.csv")
```

